### ISSUE TITLE
Multiversion in lieu of compiling from source with RUSTFLAGS="-C target-cpu=native"

### ISSUE THREAD

**Issue by smu160** [LaihoE/SIMD-itertools#7]
Hi @LaihoE,

I was wondering if you are open to uitilizing the [multiversion](https://crates.io/crates/multiversion) crate to utilize dyanamic dispatch, rather than having users compile from source (to get the best performance). 

I use multiversion for my own project and it's great! You can see example usage [here](https://github.com/QuState/PhastFT/blob/08eedcb6f877787fd6c5efd56b0c4e6df299eb2b/src/lib.rs#L113-L120).

I can run a before/after benchmark using your existing benchmarks to check for any regressions.

Thank you!

**Comment by LaihoE** [comment]
Yes, multiversion seems like the way to go. Do you want implement it?

**Comment by smu160** [comment]
@LaihoE 

I'll start on a PR for this issue once the benchmarks PR is sorted out. That way, I can easily establish a baseline to test for regressions. Thank you!!

**Comment by LaihoE** [comment]
Sorry if you were working on this, It is just blocking some future ideas with SIMD_LEN, so I went ahead and added multiversioning.

**Comment by smu160** [comment]
@LaihoE All good! Apologies for the delays.
